Added authorization with files
oleh-skoromnyi/education-portal pull request #2
Opened 2021-05-12 12:12 UTC by oleh-skoromnyi

Added authorization with files and console command processor.

2021-05-23 10:59 UTC, vladimir-shirmanov requested changes
В принципе неплохо, но очень мало кода и все в одном проекте. Разнеси это по разным проектам, структура у тебя уже готова, думаю много времени это не займет и поправь комментарии мои и можно двигаться дальше. И еще, сейчас приложение просто падает если я ввожу не существующий логин,  это тоже надо исправить

2021-05-23 10:59 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal/BusinessLogic/Authorization.cs
> +            if(temp.Password == password)
Пароли не надо хранить в открытом виде в БД. Тогда разрабы имеют доступ к акам пользователей что делает систему очень уязвимой

2021-05-23 10:59 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal/BusinessLogic/IDbContext.cs
> +        public bool SaveUser(User user);
почему только юзер? Разве контекст работает только с одним типом?

2021-05-23 10:59 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal/BusinessLogic/User.cs
> +        //public string Name { get; private set; }
закоменченого кода не должно быть в ПР и комитах

2021-05-23 10:59 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal/BusinessLogic/User.cs
> +        public User()
зачем этот пустой конструктор?

2021-05-23 10:59 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal/DataAccess/FileDb.cs
> +                File.WriteAllText($"{user.Login}.db", jsonString);
А тебе не кажется нерациональным использовать под каждую сущность отдельный файл? почему не хранить это все в одном файле?

2021-05-23 10:59 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal/DataAccess/FileDb.cs
> +                User user = (User)JsonSerializer.Deserialize(jsonString, userType);
Deserialize есть  женерик метод. Лучше использовать его, тогда не придется тип получать, на одно действие меньше

2021-05-23 10:59 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal/Program.cs
> +            FileDb database = new FileDb();
можно было бы уже прикрутить IoC контейнер

2021-05-23 10:59 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal/Program.cs
> +            //commandDictionary.Add("Logout", new LogoutCommand());
опять закоменченный код

2021-05-23 10:59 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal/UI/CommandManager.cs
> +            while (input != "Exit")
Почему тут какие то magic strings?

2021-05-23 10:59 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal/UI/CommandProcessor.cs
> +        Dictionary<string, ICommand> commands;
использовать строки в качестве ключа, да еще и ожидать что пользователь введет правильно названия команд, довольно наивно

2021-05-23 10:59 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal/UI/LoginCommand.cs
> +        public LoginCommand(Authorization auth)
Тут лучше использовать интерфейс что бы была возможность протестировать данный класс

2021-05-26 16:59 UTC, oleh-skoromnyi commented on EducationPortal/EducationPortal/BusinessLogic/Authorization.cs
> +            if(temp.Password == password)
Добавил хеширование паролей алгоритмом SHA512.

2021-05-26 17:00 UTC, oleh-skoromnyi commented on EducationPortal/EducationPortal/BusinessLogic/IDbContext.cs
> +        public bool SaveUser(User user);
Сделал IDbContext дженерик интерфейсом.

2021-05-26 17:00 UTC, oleh-skoromnyi commented on EducationPortal/EducationPortal/BusinessLogic/User.cs
> +        //public string Name { get; private set; }
Убрал комментарии.

2021-05-26 17:01 UTC, oleh-skoromnyi commented on EducationPortal/EducationPortal/BusinessLogic/User.cs
> +        public User()
Пустой конструктор нужен для десериализации из json.

2021-05-26 17:02 UTC, oleh-skoromnyi commented on EducationPortal/EducationPortal/DataAccess/FileDb.cs
> +                File.WriteAllText($"{user.Login}.db", jsonString);
Сделал хранение в сущностей в одном файле.

2021-05-26 17:03 UTC, oleh-skoromnyi commented on EducationPortal/EducationPortal/DataAccess/FileDb.cs
> +                User user = (User)JsonSerializer.Deserialize(jsonString, userType);
Использовал дженерик метод десериализации.

2021-05-26 17:06 UTC, oleh-skoromnyi commented on EducationPortal/EducationPortal/Program.cs
> +            FileDb database = new FileDb();
Добавил Autofac.

2021-05-26 17:06 UTC, oleh-skoromnyi commented on EducationPortal/EducationPortal/Program.cs
> +            //commandDictionary.Add("Logout", new LogoutCommand());
Убрал комментарии в коде.

2021-05-26 17:07 UTC, oleh-skoromnyi commented on EducationPortal/EducationPortal/UI/CommandManager.cs
> +            while (input != "Exit")
Вынес выход в отдельную команду. Условие цикла поменял на true.

2021-05-26 17:11 UTC, oleh-skoromnyi commented on EducationPortal/EducationPortal/UI/CommandProcessor.cs
> +        Dictionary<string, ICommand> commands;
Если пользователь введёт команду не правильно, то выведется сообщение "Command not found. Press ENTER and try again." и будет заново предложен ввод, также добавил вызов ToLower, чтобы игнорировать регист введённой команды.

2021-05-26 17:11 UTC, oleh-skoromnyi commented on EducationPortal/EducationPortal/UI/LoginCommand.cs
> +        public LoginCommand(Authorization auth)
Добавил интерфейс IAuth и заменил все Authorization на IAuth.

2021-05-26 17:13 UTC, oleh-skoromnyi commented on EducationPortal/EducationPortal/UI/LoginCommand.cs
> +        public LoginCommand(Authorization auth)
Также исправил ошибку вылета программы при вводе не существующего логина.

2021-06-30 09:50 UTC, merged